image: alpine:latest

variables:
  GIT_STRATEGY: clone

before_script:
  - apk add --no-cache bash git gnupg jq

stages:
  - test

unit_tests:
  stage: test
  script:
    - echo "Running unit tests..."
    - |
      for test in tests/*.test; do
        echo "Running $test"
        bash "$test"
      done
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
